version: '2'
services:
  imdbpy:
    image: guruparvesh/imdbpy
    #container_name: imdbpy
    restart: always
    expose:
     - 5000
  openresty:
    image: guruparvesh/openresty
    #container_name: openresty
    restart: always
    ports: 
     - 8080:8080
